http:
  host: 'localhost'
  port: 3000
  
db: 
  type: 'postgres'
  port: 5432
  database: 'escro_table'
  username: 'postgres'
  password: '1568'

jwt:
  expiresIn: 3600
  access_secret: 'access1234'
  refresh_secret: 'refresh1234'